name: Deploy to Staging

on:
  push:
    branches: [ "staging-from-main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}

      # PRE-TRUST the server host key to avoid "Host key verification failed"
      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -T 20 -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync code to server
        run: |
          RSYNC_FLAGS="-az --delete --omit-dir-times --no-perms --exclude .git/ --exclude .github/"
          rsync $RSYNC_FLAGS -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }}:${{ secrets.STAGING_PATH }}/

      - name: Post-deploy (cache flush, rewrites, health)
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} "\
            cd ${{ secrets.STAGING_PATH }} && \
            chmod +x ops/*.sh || true && \
            ./ops/post_deploy.sh '${{ secrets.STAGING_PHP }}' || true"
