name: Deploy to Staging

on:
  push:
    branches: [ "staging-from-main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts

      - name: Create release archive
        run: tar -czf release.tgz --exclude .git --exclude .github .

      - name: Upload release archive
        run: scp release.tgz ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }}:${{ secrets.STAGING_PATH }}/

      - name: Deploy on server
        run: |
          ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} << 'EOF'
            cd ${{ secrets.STAGING_PATH }}
            tar -xzf release.tgz
            rm -f release.tgz
            chmod +x ops/*.sh || true
            ./ops/post_deploy.sh '${{ secrets.STAGING_PHP }}'
          EOF
